### ISSUE TITLE
Blueprint lines align with in-game blocks

### ISSUE THREAD

**Issue by inverspe** [Alyosha015/Stormworks-Image-To-Paintblock#1]
Make it so the lines would perfectly align the blocks
![20230118105943_1](https://user-images.githubusercontent.com/80278067/213072014-0bbf6c22-2b93-4e85-87d1-c605719e1fde.jpg)

**Comment by Alyosha015** [comment]
I've thought of doing something similar to that, by just having two numeric textboxes which can shift the image by up to 8 pixels in any direction manually. I think making an automatic version wouldn't be possible, because the program wouldn't know which lines to use to align the image out of the hundreds or thousands on a blueprint.

**Comment by inverspe** [comment]
> I've thought of doing something similar to that, by just having two numeric textboxes which can shift the image by up to 8 pixels in any direction manually. I think making an automatic version wouldn't be possible, because the program wouldn't know which lines to use to align the image out of the hundreds or thousands on a blueprint.

late response but maybe you can implement that? if not it's perfectly fine.
